# Generated by Django 2.2.3 on 2019-07-02 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='genres',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Genre'),
        ),
    ]
