# Generated by Django 2.2.3 on 2019-07-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boost',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
